---
title: "ADSC4050 Principal Component Analysis II Examples"
author: "Sean Hellingman"
format: html
editor: visual
---

# Part I

## Illustrative Example 1

```{r}

# 1 #

set.seed(4050)
dataMatrix <- matrix(rnorm(400), nrow = 40)
image(1:10, 1:40, t(dataMatrix)[, nrow(dataMatrix):1])

heatmap(dataMatrix)

round(cor(dataMatrix),digits = 2)


```

```{r}
# 2 #

set.seed(4050)

for (i in 1:40) {
     coinFlip <- rbinom(1, size = 1, prob = 0.5)
     
     ## If coin is heads add a common pattern to that row
     if (coinFlip) {
         dataMatrix[i, ] <- dataMatrix[i, ] + rep(c(0, 3), each = 5)
     }
 }

image(1:10, 1:40, t(dataMatrix)[, nrow(dataMatrix):1])

heatmap(dataMatrix)

round(cor(dataMatrix),digits = 2)
```

## Illustrative Example 2

```{r}

library(dplyr)

hh <- dist(dataMatrix) %>% hclust
dataMatrixOrdered <- dataMatrix[hh$order, ]
par(mfrow = c(1, 3))

## Complete data
image(t(dataMatrixOrdered)[, nrow(dataMatrixOrdered):1])
 
## Show the row means
plot(rowMeans(dataMatrixOrdered), 40:1, , xlab = "Row Mean", ylab = "Row", pch = 19)
 
## Show the column means
plot(colMeans(dataMatrixOrdered), xlab = "Column", ylab = "Column Mean", pch = 19)


```

## Illustrative Example 3

```{r}



library(plotly)

set.seed(4050)

# ------------------------------------------------------------
# 1. Generate correlated 3D data with strong anisotropy
# ------------------------------------------------------------

n <- 400

x <- rnorm(n, 0, 6)
y <- 0.8 * x + rnorm(n, 0, 2)
z <- 0.5 * x - 0.3 * y + rnorm(n, 0, 1.5)

data <- data.frame(x, y, z)

# ------------------------------------------------------------
# 2. Perform PCA on covariance matrix (NO scaling)
# ------------------------------------------------------------

pca <- prcomp(data, scale. = FALSE)

# Principal directions (eigenvectors)
pcs <- pca$rotation

# Standard deviations of PCs (sqrt eigenvalues)
pc_sd <- pca$sdev

# Center of the data
center <- colMeans(data)

# ------------------------------------------------------------
# 3. Scale vectors by variability explained
# ------------------------------------------------------------

# Arrow scaling factor (visual tuning)
arrow_scale <- 3

# Vectors proportional to sqrt(eigenvalues)
pc_vectors <- pcs %*% diag(pc_sd) * arrow_scale

# ------------------------------------------------------------
# 4. Compute variance explained (for labels)
# ------------------------------------------------------------

var_explained <- (pc_sd^2) / sum(pc_sd^2)

labels <- paste0(
  "PC", 1:3,
  " (", round(var_explained * 100, 1), "%)"
)

# ------------------------------------------------------------
# 5. Create 3D scatter plot
# ------------------------------------------------------------

p <- plot_ly(
  data,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(
    size = 3,
    opacity = 0.6
  ),
  name = "Data"
)

# ------------------------------------------------------------
# 6. Add PCA vectors
# ------------------------------------------------------------

for (i in 1:3) {

  p <- add_trace(
    p,
    x = c(center[1], center[1] + pc_vectors[1, i]),
    y = c(center[2], center[2] + pc_vectors[2, i]),
    z = c(center[3], center[3] + pc_vectors[3, i]),
    type = "scatter3d",
    mode = "lines",
    line = list(width = 8),
    name = labels[i]
  )
}

# ------------------------------------------------------------
# 7. Display interactive plot
# ------------------------------------------------------------

p
```

## Example 1 from slides

```{r}


Ball <- read.csv("Basketball.csv")

BallNum <- Ball %>% 
  select_if(is.numeric)

library(plotly)


fig <- plot_ly(Ball, x = ~PF, y = ~PTS, z = ~TRB, color = ~Pos, colors = c('black', 'blue', 'orange','darkgreen','violet'))

fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'Personal Fouls'),
                     yaxis = list(title = 'Points'),
                     zaxis = list(title = 'Total Rebounds')))

fig





# fig1 <- plot_ly(Ball, x = ~scale(PF), y = ~scale(PTS), z = ~scale(TRB), color = ~Pos, colors = c('black', 'blue', 'orange','darkgreen','violet'))
# 
# fig <- fig %>% add_markers()
# fig <- fig %>% layout(scene = list(xaxis = list(title = 'Personal Fouls'),
#                      yaxis = list(title = 'Points'),
#                      zaxis = list(title = 'Total Rebounds')))
# 
# fig1


```

```{r}


# rownames(Ball) <- Ball[,1]

# 2 #

Cor <- Ball %>% 
  select_if(is.numeric) %>% 
  cor()

# 3 #

E.1 <- eigen(Cor)


# 4 #

E.1

sum(E.1$values)

# Amount of variability
round(E.1$values/sum(E.1$values),digits = 2)


# 5 #
round(E.1$vectors,digits = 2)
# rows correspond to original variables
# columns correspond to each PC

# Loadings #

loadings <- E.1$vectors %>% 
  as.data.frame() %>% 
  select(V1:V3) %>% 
  data.frame(row.names = colnames(BallNum)) %>% 
  rename("PC1" = V1, "PC2" = V2, "PC3" = V3) %>% 
  round(digits = 3)

loadings

# Interpretation based on magnitude and direction #
# Most important has the largest magnitude #

# 6 #

rownames(BallNum) <- Ball[,1]
PC.scores <- scale(BallNum) %*% E.1$vectors
head(PC.scores[,1:2])

# Are they orthoginal?
round(cor(PC.scores),digits = 3)
```

```{r}

# From Illustrative Example 3

Cor2 <- cor(data)

eigen(Cor2)
```

# Part II

## Example 1 from slides

```{r}


# data.PCA <- princomp(data,
#          cor = TRUE)
# 
# screeplot(data.PCA)
# plot(data.PCA)
```

## Illustrative Example 1

```{r}

library(h2o)


h2o.no_progress()  # turn off progress bars for brevity
h2o.init(max_mem_size = "5g")

# convert data to h2o object
my_basket.h2o <- as.h2o(iris)

# run PCA
my_pca <- h2o.prcomp(
  training_frame = my_basket.h2o,
  pca_method = "GramSVD",
  k = ncol(iris), 
  transform = "STANDARDIZE", 
  impute_missing = TRUE,
  max_runtime_secs = 1000
)


my_pca

# Vectors #

my_pca@model$eigenvectors


## Which features contribute most to PC1 ##

my_pca@model$eigenvectors %>% 
  as.data.frame() %>% 
  mutate(feature = row.names(.)) %>%
  ggplot(aes(pc1, reorder(feature, pc1))) +
  geom_point()


## Contributions to PC1 and PC2 ##

my_pca@model$eigenvectors %>% 
  as.data.frame() %>% 
  mutate(feature = row.names(.)) %>%
  ggplot(aes(pc1, pc2, label = feature)) +
  geom_text()

```

## Example 2 from slides

```{r}

library(h2o)


h2o.no_progress()  # turn off progress bars for brevity
h2o.init(max_mem_size = "5g")

# convert data to h2o object
my_basket.h2o <- as.h2o(BallNum)



```

## Illustrative Example 2

```{r}


# Base R #

Data.PCA <- princomp(iris[,1:4],cor = TRUE)
summary(Data.PCA, loadings = TRUE, cutoff = 0)

eigen.prop <- Data.PCA$sdev / sum(Data.PCA$sdev)
barplot(eigen.prop)
abline(h = mean(eigen.prop), col = "red") # Add average line

# h2o #

data.frame(
  PC  = my_pca@model$importance %>% seq_along,
  PVE = my_pca@model$importance %>% .[2,] %>% unlist()
) %>%
  ggplot(aes(PC, PVE, group = 1, label = PC)) +
  geom_point() +
  geom_line() +
  geom_text(nudge_y = -.02)

```

## Example 3 from slides

```{r}




```

## Example Plotting Code

```{r}

data.frame(
  PC  = my_pca@model$importance %>% seq_along(),
  PVE = my_pca@model$importance %>% .[2,] %>% unlist(),
  CVE = my_pca@model$importance %>% .[3,] %>% unlist()
) %>%
  tidyr::gather(metric, variance_explained, -PC) %>%
  ggplot(aes(PC, variance_explained)) +
  geom_point() +
  facet_wrap(~ metric, ncol = 1, scales = "free")

```

## Example 4 from slides

```{r}



```

## Example 5 from slides

```{r}



```

## Illustrative Example 3

```{r}

library(randomForest)
library(rsample)
library(caret)

set.seed(4050)

iris_split <- initial_split(iris, prop = 0.8) 

# Extract the training and testing data frames
train_data <- training(iris_split)
test_data <- testing(iris_split)


# Keep response out of PCA 
train_X <- train_data[, 1:4]
train_y <- train_data$Species

# PCA
pca_obj <- princomp(train_X, cor=TRUE)
pca_obj

pca_obj$sdev / sum(pca_obj$sdev)

# Transform data (Scores)
train_pca <- predict(pca_obj, train_X)

# Select Components
train_components <- train_pca[,1:3]

# Random forest

model.1 <- randomForest(x = train_components,
                        y = train_y,
                        mtry = 2,
                        ntree = 500
)


# Format testing data (multiply by loadings)
test_X <- test_data[, 1:4]
test_pca <- predict(pca_obj, test_X)
test_pca_selected <- test_pca[, 1:3]


# Accuracy 

confusionMatrix(test_data$Species,
                predict(model.1,test_pca_selected,type = "class"))

```

## Example 6 from slides

```{r}

set.seed(4050)

BallNumScale <- as.data.frame(scale(BallNum))
BallNumScale$Pos <- Ball$Pos

Ball_split <- initial_split(BallNumScale, prop = 0.8) 

# Extract the training and testing data frames
train_data <- training(Ball_split)
test_data <- testing(Ball_split)



```
