---
title: "ADSC4050 Random Forests Examples"
author: "Sean Hellingman"
format: html
editor: visual
---

```{r}
# Helper packages
library(dplyr)    
library(ggplot2)  

# Modelling packages

library(h2o)      # a java-based implementation of random forest
```

## Example 1 from slides

```{r}

library(randomForest)
library(rsample)

data(diamonds)

diamonds <- diamonds %>% 
  relocate(price)

set.seed(4050)

diamonds_split <- initial_split(diamonds, prop = 0.8) 

# Extract the training and testing data frames
train_data <- training(diamonds_split)
test_data <- testing(diamonds_split)

# RF model <- randomForest(Y ~ X1 + ... + XP,
#   data = Wages,
#   mtry = m,
#   importance = TRUE,
#   ntree = 500)
# 
# plot(RF model) # To plot OOB sample error

```

## Example 2 from slides 

```{r}


# RF model <- randomForest(Y ~ X1 + ... + XP,
#   data = Wages,
#   mtry = m,
#   importance = TRUE,
#   ntree = 500)
# 
# plot(RF model) # To plot OOB sample error


```

## Grid Search Illustrative Example

```{r}


Wages <- read.csv("Wages.csv")

n_features <- length(setdiff(names(Wages), "Salary"))

library(ranger)   # a c++ implementation of random forest 

# create hyperparameter grid
hyper_grid <- expand.grid(
  mtry = floor(n_features * c(.05, .15, .25, .333, .4)),
  min.node.size = c(1, 3, 5, 10), 
  replace = c(TRUE, FALSE),                               
  sample.fraction = c(.5, .63, .8),                       
  rmse = NA                                               
)

# execute full cartesian grid search
for(i in seq_len(nrow(hyper_grid))) {
  # fit model for ith hyperparameter combination
  fit <- ranger(
    formula         = Wages ~ ., 
    data            = Wages, 
    num.trees       = n_features * 10,
    mtry            = hyper_grid$mtry[i],
    min.node.size   = hyper_grid$min.node.size[i],
    replace         = hyper_grid$replace[i],
    sample.fraction = hyper_grid$sample.fraction[i],
    verbose         = FALSE,
    seed            = 4050,
    respect.unordered.factors = 'order',
  )
  # export OOB error 
  hyper_grid$rmse[i] <- sqrt(fit$prediction.error)
}

# assess top 10 models
hyper_grid %>%
  arrange(rmse) %>%
  head(10)



```

## Example 3 from slides

```{r}








# ames_rf1 <- ranger(
#   price ~ .,
#   data = train_data,
#   mtry = floor(n_features / 3),
#   respect.unordered.factors = "order",
#   seed = 123
# )
# 
# # get OOB RMSE
# (default_rmse <- sqrt(ames_rf1$prediction.error))


```

## Example 4 from slides

```{r}

library(caret)

# Pred <- predict(model,test_data)
# Pred$predictions
# 
# metrics <- postResample(pred = Pred$predictions, obs = test_data$price)
# print(metrics)
```

## Example 5 from slides

```{r}

library(vip)


# rf_impurity <- ranger(
#   formula = y ~ ., 
#   data = train,
#   num.trees = 2000, # many trees
#   mtry = 32,
#   min.node.size = 1,
#   sample.fraction = .80,
#   replace = FALSE,
#   importance = "impurity",
#   respect.unordered.factors = "order",
#   verbose = FALSE,
#   seed  = 4050
# )
# 
# # re-run model with permutation-based variable importance
# rf_permutation <- ranger(
#   formula = y ~ ., 
#   data = train, 
#   num.trees = 2000,
#   mtry = 32,
#   min.node.size = 1,
#   sample.fraction = .80,
#   replace = FALSE,
#   importance = "permutation",
#   respect.unordered.factors = "order",
#   verbose = FALSE,
#   seed  = 4050
# )

vip(model)
```
